"""Deterministic KB documents (spec §11.2): exact, cheap, regenerated on every refresh."""

from __future__ import annotations

from forge.kb.facts import RepoFacts, layout_rules
from forge.kb.python_index import ModuleFacts

GENERATED_NOTE = (
    "_Generated by Forge from the code. To keep your own edits, add a line containing only "
    "`<!-- pinned -->`._"
)


def stack_md(facts: RepoFacts) -> str:
    stack = facts.stack
    lines = [
        f"# Stack\n\n{GENERATED_NOTE}\n",
        f"- Python app folder: `{facts.app_subfolder}/`",
        f"- Python (app venv): {stack.python_version or 'unknown'}",
    ]
    if stack.packages:
        lines.append(
            "- Key packages: "
            + ", ".join(
                f"{name} {version}"
                for name, version in stack.packages.items()
                if name in _KEY or len(stack.packages) <= 15
            )
        )
    lines.append(f"- Requirement files: {', '.join(stack.requirement_files) or 'none found'}")
    lines.append(f"- Tests: {stack.test_runner or 'none detected'}")
    lines.append(f"- Lint/format: {', '.join(stack.lint_tools) or 'none configured'}")
    lines.append(f"- Type checking: {stack.type_checker or 'none configured'}")
    if facts.unparsable:
        lines.append(f"- Files Python could not parse: {', '.join(facts.unparsable)}")
    return "\n".join(lines) + "\n"


_KEY = {
    "flask",
    "flask-smorest",
    "marshmallow",
    "sqlalchemy",
    "psycopg",
    "psycopg2",
    "psycopg2-binary",
    "langchain",
    "langchain-core",
    "langchain-openai",
    "langgraph",
    "pydantic",
    "pytest",
    "pyjwt",
    "alembic",
}


def commands_md(facts: RepoFacts) -> str:
    commands = facts.commands
    sections = [
        ("Run the app", commands.run),
        ("Tests", commands.test),
        ("Lint / type check", commands.lint),
        ("Other", commands.other),
    ]
    lines = [f"# Commands\n\n{GENERATED_NOTE}\n", f"Run from `{facts.app_subfolder}/` with the app's venv.\n"]
    for title, items in sections:
        lines.append(
            f"## {title}\n" + ("\n".join(f"    {item}" for item in items) if items else "None found.") + "\n"
        )
    if commands.sources:
        lines.append("Sources: " + ", ".join(commands.sources))
    return "\n".join(lines) + "\n"


def api_catalog_md(facts: RepoFacts) -> str:
    lines = [f"# API catalog\n\n{GENERATED_NOTE}\n", "## Blueprints\n"]
    for blueprint in facts.blueprints:
        registered = ", ".join(blueprint.registered_in) or "NOT REGISTERED"
        lines.append(
            f"- `{blueprint.name}` url_prefix `{blueprint.url_prefix or '/'}` — "
            f"{blueprint.path}:{blueprint.line}; "
            f"registered at {registered}"
        )
    lines.append("\n## Endpoints\n")
    lines.append("| Method | Path | View | Request | Response | Other decorators | Where |")
    lines.append("|---|---|---|---|---|---|---|")
    for endpoint in facts.endpoints:
        lines.append(
            f"| {endpoint.method} | `{endpoint.path}` | {endpoint.view} ({endpoint.style}) | "
            f"{', '.join(endpoint.arguments) or '-'} | {', '.join(endpoint.responses) or '-'} | "
            f"{', '.join(endpoint.other_decorators) or '-'} | {endpoint.file}:{endpoint.line} |"
        )
    if not facts.endpoints:
        lines.append("No flask-smorest endpoints found.")
    return "\n".join(lines) + "\n"


def db_schema_md(facts: RepoFacts) -> str:
    lines = [
        f"# Database schema\n\n{GENERATED_NOTE}\n",
        "Live introspection is added with the database milestone (M7); "
        "this is from the code and SQL scripts.\n",
        "## SQLAlchemy models\n",
    ]
    for model in facts.models:
        lines.append(f"### `{model.table}` — {model.class_name} ({model.path}:{model.line})\n")
        for column in model.columns:
            flags = [
                f
                for f, on in (("PK", column.primary_key), (f"FK -> {column.foreign_key}", column.foreign_key))
                if on
            ]
            lines.append(f"- `{column.name}` {column.type}" + (f" ({', '.join(flags)})" if flags else ""))
        lines.append("")
    if not facts.models:
        lines.append("None found.\n")
    scripts = facts.sql_scripts
    lines.append("## SQL scripts\n")
    if scripts.folder:
        lines.append(
            f"Folder `{scripts.folder}/`, naming {scripts.naming or 'not uniform'}"
            + (f"; next script: `{scripts.next_name_example}`" if scripts.next_name_example else "")
            + "\n"
        )
        lines += [f"- `{t.table}` ({t.script}): {', '.join(t.columns)}" for t in scripts.tables]
    else:
        lines.append("No SQL scripts found.")
    lines.append("\n## Raw SQL usage (which code touches which table)\n")
    for usage in [u for u in facts.sql_usage if not u.in_tests]:
        qualified = (
            " — **schema-qualified: not redirected to a scratch schema**" if usage.schema_qualified else ""
        )
        lines.append(
            f"- {usage.operation} {', '.join(usage.tables) or '?'} — {usage.module}.{usage.function} "
            f"({usage.path}:{usage.line}){qualified}"
        )
    if facts.bootstraps:
        lines.append("\n## Credentials bootstrap (spec §9.5.1)\n")
        for boot in facts.bootstraps:
            lines.append(
                f"- {boot.module}.{boot.function} ({boot.path}:{boot.line}) reads table(s) "
                f"{', '.join(f'`{t}`' for t in boot.tables)} and sets env vars {', '.join(boot.env_names)}. "
                "Values are secret: this table is on Forge's read deny-list once confirmed."
            )
    return "\n".join(lines) + "\n"


def llm_graphs_md(facts: RepoFacts) -> str:
    lines = [f"# LLM graphs\n\n{GENERATED_NOTE}\n"]
    for graph in facts.graphs:
        where = f"{graph.path}:{graph.line}" + (f" in `{graph.builder}()`" if graph.builder else "")
        lines += [
            f"## `{graph.variable}` = StateGraph({graph.state_type}) — {where}\n",
            f"- State: {'; '.join(graph.state_fields) or graph.state_type}",
            f"- Nodes: {', '.join(f'{name} ({fn})' for name, fn in graph.nodes)}",
            f"- Edges: {', '.join(f'{a} -> {b}' for a, b in graph.edges)}",
        ]
        for source, router, mapping in graph.conditional:
            targets = ", ".join(f"{k} -> {v}" for k, v in mapping.items()) or "(see router)"
            lines.append(f"- Conditional from {source} via `{router}`: {targets}")
        lines.append(f"- Compiled: {'yes' if graph.compiled else 'no'}\n")
    if not facts.graphs:
        lines.append("No LangGraph graphs found.")
    return "\n".join(lines) + "\n"


def module_facts_md(package: str, modules: list[ModuleFacts]) -> str:
    """The deterministic half of modules/<package>.md; the narrative is added by the LLM."""
    lines = [f"## Facts ({len(modules)} file(s))\n"]
    for facts in modules:
        lines.append(f"### {facts.path}")
        for symbol in facts.symbols:
            if symbol.kind == "class":
                bases = f"({', '.join(symbol.bases)})" if symbol.bases else ""
                lines.append(
                    f"- class `{symbol.name}{bases}` line {symbol.line}"
                    + (f" — {symbol.doc}" if symbol.doc else "")
                )
            elif symbol.qualname.count(".") <= 1:
                decorators = " ".join(f"@{d}" for d in symbol.decorators)
                lines.append(
                    f"- `{symbol.signature}` line {symbol.line}" + (f" {decorators}" if decorators else "")
                )
        lines.append("")
    return "\n".join(lines)


def essentials(facts: RepoFacts, conventions: str | None) -> str:
    """Pinned 'codebase essentials' (spec §10.2, ≤1.5k tokens)."""
    stack = facts.stack
    lines = [
        f"Python app in `{facts.app_subfolder}/`; Python {stack.python_version or '?'}; "
        + ", ".join(f"{n} {v}" for n, v in stack.packages.items() if n in _KEY)
    ]
    lines += [f"- {rule}" for rule in layout_rules(facts)]
    if facts.commands.test:
        lines.append(f"- Test: `{facts.commands.test[0]}`")
    if facts.commands.run:
        lines.append(f"- Run: `{facts.commands.run[0]}`")
    for boot in facts.bootstraps:
        lines.append(
            f"- DB credentials come from table `{', '.join(boot.tables)}` via "
            f"{boot.module}.{boot.function} (secret values)"
        )
    lines.append(
        "- More: kb_search / kb_read (docs: STACK, ARCHITECTURE, CONVENTIONS, COMMANDS, API_CATALOG, "
        "DB_SCHEMA, "
        "LLM_GRAPHS, modules/<package>), find_symbol, find_references, list_symbols."
    )
    if conventions:
        lines.append("\nTop conventions:\n" + conventions)
    return "\n".join(lines)
